services:
    gokapi:
        image: f0rc3/gokapi:latest
        environment:
            - TZ=Asia/Seoul
        ports:
            - 53842:53842
        volumes:
            - ./gokapi-config:/app/config
            - ./gokapi-data:/app/data
