version: '3.5'
services:
  sqlpad:
    container_name: sqlpad
    image: "sqlpad/sqlpad:latest"
    restart: always
    ports:
      - 8000:3000
    environment:
      - SQLPAD_ADMIN=admin@sqlpad.com
      - SQLPAD_ADMIN_PASSWORD=83Wrw50
    volumes:
      - /mnt/sqlpad:/var/lib/sqlpad
